<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2017/08/18 18:19:37

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:dbname=mytick;host=localhost',
  'profiler' => false,
  'username' => 'mytick',
  'password' => 'mytick',
  'attributes' => 
  array (
    'quote_identifier' => true,
  ),
  'name' => 'doctrine',
)),);
