<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2017/08/18 13:24:08
sfConfig::add(array(
  'mod_projectsphases_enabled' => true,
  'mod_projectsphases_view_class' => 'sfPHP',
));
