<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2017/08/18 13:22:57
sfConfig::add(array(
  'mod_projectscomments_enabled' => true,
  'mod_projectscomments_view_class' => 'sfPHP',
));
