<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2017/08/18 13:26:37
sfConfig::add(array(
  'mod_discussionscomments_enabled' => true,
  'mod_discussionscomments_view_class' => 'sfPHP',
));
