<?php
// auto-generated by sfSecurityConfigHandler
// date: 2017/08/18 13:22:46
$this->security = array (
  'ldap' => 
  array (
    'is_secure' => false,
  ),
  'restorepassword' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => true,
  ),
);
